project:
  type: website
  output-dir: docs
lang: es
website:
  title: "R aplicado a Ecología"
  navbar:
    left:
      - text: "Unidad 01"
        href: ./unidades/unidad_01.qmd
      - text: "Unidad 02"
        href: ./unidades/unidad_02.qmd
      - text: "Unidad 03"
        href: ./unidades/unidad_03.qmd
      - text: "Unidad 04"
        href: ./unidades/unidad_04.qmd
      - text: "Unidad 05"
        href: ./unidades/unidad_05.qmd

execute:
  output: false
  warning: false
  eval: false
date: now
date-format: YYYY
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    code-copy: true
    number-sections: true
    smooth-scroll: true
